// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrIQlOeGlmH3mGeeLho1d3ws2eLeriBHo',
    appId: '1:798152230815:web:7fc885211dc981156a5faa',
    messagingSenderId: '798152230815',
    projectId: 'unigo-cd46d',
    authDomain: 'unigo-cd46d.firebaseapp.com',
    storageBucket: 'unigo-cd46d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyT02829QStmdrXSWfjwf34akYBZmhdrE',
    appId: '1:798152230815:android:8e9646f8532656e46a5faa',
    messagingSenderId: '798152230815',
    projectId: 'unigo-cd46d',
    storageBucket: 'unigo-cd46d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV9cpEYeuVc4IavnmR8d1hK3kDK3fIuxA',
    appId: '1:798152230815:ios:cfe5279b0fdba7ba6a5faa',
    messagingSenderId: '798152230815',
    projectId: 'unigo-cd46d',
    storageBucket: 'unigo-cd46d.appspot.com',
    iosBundleId: 'com.example.eaFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV9cpEYeuVc4IavnmR8d1hK3kDK3fIuxA',
    appId: '1:798152230815:ios:cfe5279b0fdba7ba6a5faa',
    messagingSenderId: '798152230815',
    projectId: 'unigo-cd46d',
    storageBucket: 'unigo-cd46d.appspot.com',
    iosBundleId: 'com.example.eaFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrIQlOeGlmH3mGeeLho1d3ws2eLeriBHo',
    appId: '1:798152230815:web:8d21d7e7ad5ee68c6a5faa',
    messagingSenderId: '798152230815',
    projectId: 'unigo-cd46d',
    authDomain: 'unigo-cd46d.firebaseapp.com',
    storageBucket: 'unigo-cd46d.appspot.com',
  );
}
